# ENCRYPT BEFORE COMMITTING:  sops -e -i apps/homelab/honcho/honcho-secret.yaml
# DB_CONNECTION_URI: use HONCHO_DB_PASSWORD from apps/homelab/postgres/postgres-secret.yaml
# AUTH_JWT_SECRET:   openssl rand -hex 32
# LLM_GEMINI_API_KEY: from https://aistudio.google.com/apikey
apiVersion: v1
kind: Secret
metadata:
    name: honcho-secrets
stringData:
    DB_CONNECTION_URI: ENC[AES256_GCM,data:KH7RhqZol9QzFwLpbU66L5PuiQpKyM3D8u+d3lXHEAP8/U0LwRqEzSpIz4rPHPYX8UXHpa8wLXS6Or+PE8YGghmlh7hj46EYvFLzkn/z1GEeEoM4AiM2KvU2TH8piWrG8wnW7rSw1GE=,iv:yW+adFn81s3T4n+pEYv/A2T4DGvaU+a0FUV3GfuKT1I=,tag:9VHJH/ZCYqUr9hLdbjoXwA==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:/z/kQHyJPboJLQEar6q8x1ERljuGMsFOWYPsOfFTd916D4zYIz3OnOiDr6ai4HoR+Ltg34wYOOlyBdODeGCTvw==,iv:Ub62D4pZqqWomMmtXqAuIjI03GlljFzFxos1ioBX8XI=,tag:r0L2uGwPkJdnzu9ENyuMgg==,type:str]
    LLM_GEMINI_API_KEY: ENC[AES256_GCM,data:uWuF10rA/Z0wb2wdGxxXTiBI+jekLR01dhUFGIVnpHU//+unIBnmbGrOHZYz3uWh/UlRU84=,iv:p8gH7Wr3AxCV7lVAFMwiNd6iHOmfUgqKsO5sGInZ21I=,tag:mDHSFu8y56+CPO4g+qF3Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMTY3MTh0RGFPeUFEaUM1
            N0UyblZoY0hHRUJLWHVKQldEZHdTbGlXUWdRCkVXVTc2VUhXbVl4ZkFLTkJlV29D
            dUNnU3VtdWpnSFpRT1lJRlkrMjd4bUUKLS0tIDNGUWhVMWFVMGZUeDdlS0dBdU5O
            OU5NS2xPbmg0M0JNZzFlV1M4V3hPamsKn7xdM1Zx9qKO8A3b5FPYtc/dg2/P06ew
            bnNMkie6rGQJs2UvgCtop41agjGQiCWpYUsW3ihLZLk3/F5CrpIaTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:16:45Z"
    mac: ENC[AES256_GCM,data:Y7RXIlLtE9m9DOrwIHIFKtxDpDxJbwLaX/4sZJqDZsKJxIRNTbIldU+xWpC48K/J3M9xUCuiK6+5sYmZlEboORxvy0ULCuFbz6MEIWCadNphRlkxrQVjqiEtZe1ICw+AYbNUTo9Y70RMzcEmxAsGkjpdpFFg5cmOAFCTH5sAoIM=,iv:Sgh869dX5c8hyamD+Emk1JI2XlO+swHjdYTC+S+vvnw=,tag:0906XjaE26fvL/hjAvasdQ==,type:str]
    version: 3.13.1
