apiVersion: v1
data:
    5c8bfccc-a58d-4db2-9f88-a8107c6ca4f7.json: ENC[AES256_GCM,data:hf0+vUJpQvMyM4zciZHRYoF6+0bTNa10wOsb6hAQev2pATLgVPvbXlAI/osXcNj5aOTeFQZFtaI9LIWvY2PyZo917zKMF5CiO0KtlfEmNrSRuxPHmhlA0/ER+z0gyw3cd8Hyk7OolnCY7U3wn1W9LIj2Em18KWtvrXlBHAdGjRXJtj0LW+W61vd+mbGMOck+AW6k6c8qnwUsr+PRlB69iw6PLLEOn42JPkmkhQjJvB2XBiR2FGLlFwMWv/wULrEXvokJX0FYKOQQ3VXeDZhgrOM2Bt6EpO87CMr7Ade2fcB//u46fXFGpM2GGGw=,iv:p/QkSp3wPbu90aHTl0d/BS8hBwBHfySbchgczIE0MvA=,tag:Oa+XTkbDu2dehxj0uhi6ng==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVEpnRlZMd2V3YmVsL1Fj
            RFA5WExuS3ZuQVRpaWVhdms1Y1lFaytsWDMwCkhaLzgxT05oVFBtVlhQLysrUjYx
            d0dxZ0JFbjZKRmpYakd3WVZPcVZrRVEKLS0tIFNuNmZiSEFzSjhnYWhoRjQ4ZXl4
            UmRsN0hORS9CQ2hFRy9Xak9FbWRRREEKlR40ItBUxLW4T9K+7TW5OaF9Bvypslpk
            VEMOOY0m+jQVsbuLfrMEcLmg//lDr1ENPUjQJQMLFg4Ww92ixyaGNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T14:55:40Z"
    mac: ENC[AES256_GCM,data:orENekGB8LYVXKcUAyVO369p2XnjOnu1Ghs+K3hVy+0QIPfLT29h/BmE6fUCfY8sP7/5cmP3zQ52tEVO6eIiFMzeAzqI6/FSeVYBz/J6mgtmrX7yvtYZoKfBM3/OostVo/6oJZFVYIIXo7Y/jT9A2Zflv2lbTSJfva4cEj5Vme4=,iv:b+D2+Y5L/h9jlHPaae2lJpt9RRW9m0lQp8/LK9S4yoc=,tag:aHdby4bRaDyc48O0ATjqAg==,type:str]
    version: 3.13.1
