apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:5Zdpg2IqDTjvqbPx,iv:M2HBimkCmfJjIOr3437mMfWlLZSgbC6c8nGKX4xjl3w=,tag:qFbBfsQfO4YRhNuu2lwdNQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:7qu3wWaLFAIooeCopTxfpVkOsUd1tZyGSPVfnCRuYn5yzu/i,iv:03UtCjCldPj/BfzULe1ZxjwH25NJF2pf21McUWPHy0o=,tag:UxkBf6Mgdb95eGqDBpYWuw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc0NIYTl4MENBTm9EY0VE
            dVNHeDAzSnNScXN6eGQzc3BuNG1zZWtBUFM4CnZpcGRaWE9XMHVoNXNGTk84a1ls
            WEhtZmY4MHVWSVQyc0t4akRtS0NxUjAKLS0tIHQzUVR6YTdYQXl6aE5TbXhEdHdy
            bm5idW9zODUvLzA0NTF0TThnejNVVGsKLoa1TWj3ID5pqF4dAD6bPI4X8zO+gVuW
            sMr+lYiLaiPolEQ5jWbJObY1vI5iCNXe5C9Y9CnnuSmR5pwmRhkoaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T15:12:37Z"
    mac: ENC[AES256_GCM,data:cLI2ILAYvhCaAsDlHkP2fM2Ja8oK2OnrTfG0sIk5HnKAtcce8BzXEJvP09Bi5nsuiz3ryXrtk9fVMMT2OckahVyUAeRIP5ps12YfdRcwA1mOrSj1bcmnJMTXHAzTupwQnJVnryaUnExA7mLBn/IZzKdXUnWPLjQtC553xReIrb8=,iv:2IifcjctrYEFkmx23ONUK++/ghalM5WdM2h3Z5cNfsU=,tag:uktM4BTdRZQvtL64qRGv0g==,type:str]
    version: 3.13.1
