apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:G7HKZBrVxoew4frDezFgUSTNyIymzxR//R8bBQp0B5gXujbdaN/zb3h/nricsrtoRWEeQuGvzHstPltvBfrCGzSGhKtObtDN,iv:Fp6auBVi6rnq5WCoht4b9KncyHZAtOxc390/JIkwxBw=,tag:Fn2VJ5XbmvztXAE8FdTTgg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYS94Z3V5Y0dxMlAwckpW
            cHlmcHJpb1JPZjJZays1ay9PMGIyS0s3U3cwCmZKaVNrM3Y4SzhvSGpTQWZTR25j
            czhIT1dqMUoxcHo3NDVqL0hRM09PK2cKLS0tIG0zZE14bkpTeVYrVzZraTJJRG5Q
            TEg1dlJpR2h3ajltQzhPeDdRTUlyL0UKsLutTITONBbRJvz5Z1PJDaD/XHQaFxvQ
            vdn8cHQLkSZ0mdJ/Bvux5MPquyTNH9ko2PzVZ3RcFps1j1b9VqtSWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T08:40:49Z"
    mac: ENC[AES256_GCM,data:eX3cxVEmQ0RUBVUb4jJ/Dj/JRf/9tFxu5faYou+GMwQTEoQoCYQAF7GhwWzan7suUIle80+TSiNrBtxBKdjkqqlx1bbNdAnaekOr7uYnJiHkIX2aCMvL049vUh4tHm8vMxE99dlW5MoZ5iG94T4/Wzlg5w3Dw/sLqvK71OPC6uI=,iv:NV7bfjMbGHvYtGrVvljsl04ogkRu7u89uiE4TmDCi3I=,tag:4OA8ydG5982CiMRQX0RC2g==,type:str]
    version: 3.13.1
