apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:evApLeZc7JX3k4wzbBoPMHKCJSEq+f4mN8heEc5qXGLzp0vQL+yBOv6DHNp4qnbsPsP3iSXPTEN/AsWjtORusQQSpk4lMW3jYIZ4kwVPnYVYJ9jsMMSntnwfFj63BWcyBiFEmtcFfJwn0/EzmX4eLABYWzu/kTChvss3DrDAvm1onJbniEAGeoKRPDucfkP4d8cqFhaJpSEzi78fO1K7nfEjdDUvM0YkD+pZWRgQS/QwkpOsG8eNCxsISlhQeOpiMlNYUgo7kpSfle9+qvIzM8SRLKF90fSUypLfrNUVUjzWdi0O1r4jCEqniCA=,iv:7zEdQN9AjO6a4dnLbmfIJ5bmQ64zek7vjA3tPqEBM+0=,tag:H3MTGdJRop4VtHAQeXeikw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTV0Z2xmdmFTRXRXbzNZ
            V1FraTl4bTQrVmtYSEsyQThwNHV3Q1pmZGc4CjV3TTdEVDg4WHBOZkJleEU4UUVl
            NkFscHhmV0d6UWk1RmgyZktud21FZjQKLS0tIFI4Vms0eGlqNlVFTmdGV1l0TGhL
            aitGd2RzS3E0ZE95WUZpMUcxNnFjUmsK3Qz7VdtsbwVSkhK5qKGtokym9xcuLz6/
            Yc9LUNxA536zA1f1baPDFJDTVNKqbE6iew2wchKk+IbL+Gf9GXH1AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T16:20:15Z"
    mac: ENC[AES256_GCM,data:vp/tfoQ83y5hCTedI/jVCGqb98J3Nhovz5N+XDi1m3UJk5JcF7Gv4JEoLtYdPyZJX2POegY6nbCj3lvGXsHQpBv8b+aIfhr+458Ib8OSNO8RbhCipxQJanxh/maNLuRquF7NVf9qetCdz2Y70WC550ZBnYYzJ3/N1PDwFPQi5P8=,iv:6g+s/+8H7cCjpr858ptmsIQlipbO/zg9f82bUvrb5Hs=,tag:qdoXB/KQMJnf5IcItKnaIg==,type:str]
    version: 3.13.1
