apiVersion: v1
data:
    password: ENC[AES256_GCM,data:aTi8ckLazej578b1J1bGF3f9Y0DL9d+0pH2/EQ==,iv:s4KZ1r+M4mqhdFXlbheb1zGDZdCLPZMNaZnRjy9Ehn0=,tag:tz2rcBDPky9GRTyhlTbgSQ==,type:str]
    user: ENC[AES256_GCM,data:SzYy+GWdQcCvNE7A,iv:iha/pU4cKuMHcRUb0DZTdQCxNWblCvxK2rXXOO40NN4=,tag:hiSTc3OHlfQB3nQhfbR0bg==,type:str]
kind: Secret
metadata:
    name: admin-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaVRPQzlreTRTTjZacUxJ
            TkxiT01EYnd1eFdSUTBtbWpWS0pQNDhSMEVJCmI4R1F1WGNwN0NkdXZTNDlNaWNE
            cE4yVVFKbmNpMFpiRzJxKytqdSt4cXcKLS0tIDREVm52ZVgyL3lldkZSQzJ4cTJl
            ZEdWM0JrVU0xRWUydXNjYXcybFBKWGcKpx3q+XCTbvgI59QgAo6yEKvW/sHMgwX/
            pbAtS5wyDa3CmAy/VObQOCUT69pg2XSTatnT1W7dmcUub/SL6TkZeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T07:51:31Z"
    mac: ENC[AES256_GCM,data:2LuruUpevY4Rfl47DnC1ym9AdYfR6yLMKroxjBScwIlbLTgEA3gf4IzSMfZRKMHjyARANU4AjRDSeq+Io1ZMBbzd0x/vPp/NOTdi/z2lgYf0165aU0XWoj4X1wSCg4XHxm39iiUBI2wDF32WrCgMggx99SmCtffxxcw2mR06HPk=,iv:PCo/aSuZ1aEvE/6i02GKIm3Cyj5y2H8awOdUosb2VDM=,tag:Y+gQXGtIMHuZOaNlYytfbQ==,type:str]
    version: 3.13.1
