#!/bin/sh
# This script assumes you have kubectl with a valid config running
# Also you should have installed SOPS and AGE, created an age keypair that is living on your cluster
# Script is made for learning practises and QoL in my homelab journey.


set -eu
trap 'stty echo' EXIT

MY_AGE_PUBLIC=YOURKEY
MY_USERNAME=YOURUSERNAME
MY_FOLDER=~/temp/secrets

printf 'Name for the secret (usually named after the app or service):'
read -r MY_SECRET_NAME

printf 'Password for %s: ' "$MY_USERNAME"
stty -echo            # hide typing
read -r MY_PASSWORD
stty echo
echo

mkdir -p "$MY_FOLDER"
OUT="${MY_FOLDER}/${MY_SECRET_NAME}-secret.yaml"

kubectl create secret generic "${MY_SECRET_NAME}-secret" \
  --from-literal=user="$MY_USERNAME" \
  --from-literal=password="$MY_PASSWORD" \
  --dry-run=client -o yaml > "$OUT"

sops --age=${MY_AGE_PUBLIC} \
--encrypt --encrypted-regex '^(data|stringData)$' --in-place "${MY_FOLDER}/${MY_SECRET_NAME}-secret.yaml"

echo "Written: $OUT"


