# ENCRYPT BEFORE COMMITTING:  sops -e -i apps/homelab/multica/multica-secret.yaml
# DATABASE_URL:   use MULTICA_DB_PASSWORD from apps/homelab/postgres/postgres-secret.yaml
# JWT_SECRET:     openssl rand -hex 32
# ALLOWED_EMAILS: your email (only these addresses can sign up / log in)
apiVersion: v1
kind: Secret
metadata:
    name: multica-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:/H3UO8/Dg+oJjP3JxfuMsthBOyweSE0K66EvVc3M22jZOnFoBbnhN/QYwC8RhqEyLTw0KE55mxwTpQg+7ZzK+84pXPDgBUdqCLRQzPlKFFMg9Rl8LBQFd/+ASqNLh5IhtxLblqNV/xqQFVkNFwfBYQ==,iv:qDb8qWm3KZodaJO9Omv8hh4Baej70L65WoVtKGNS55E=,tag:QxRGfU7/q4Qad8nXYeF6Mg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/9eL+U/SIjm9wcRyCs/JJ+W9L94lwnDiJK0Q0ncu3OUdZSaYg7u8ev+a+jXrXLj+9NQu+1QCB5hoxm7fB/GcwQ==,iv:iiipoxKfIEm8KrpfcXW6Wfi5ddaBzgYJVEBWLHaJ6JY=,tag:bIthg2p916podpkzZKVOPQ==,type:str]
    ALLOWED_EMAILS: ENC[AES256_GCM,data:99HOU5ULQBYwlGoP3PsNSp72H78=,iv:7po2pUK2+jGMmMCrU487FVkcutYzD+SmXSNsYhuVAu4=,tag:r/+jalCwHgdk9SAIrGZcBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTm8yWllETTNNR0pPL2dT
            Sm00Qk0zUE9SZFg4WE5xV2pPWnlVd0JUYVRvCkE2WSttQ0t1YTRHbklDbkZKbVpE
            VFJVVXZhbHFGeGx3N3VrWUFrNzg5WmcKLS0tIEVjNFFiRGdFRUtRMlQwa1A4NGZM
            dC9KTmJwcERVYmlvQitKYjFrMUZHdUkK4hNkQLC8rKetWxk1xIjYRbYxtQi+q5lG
            hZHnf+kWKslZo6JvTffqG1QWocRI1YYFgeI0kvxxyMX1hHzAgepPMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:16:45Z"
    mac: ENC[AES256_GCM,data:iAsrLiXxWg7PuCbv3XHtJLQmnh12u7750wPCVhjfHU8nCMoEyJ+4pcWtGSUIqx/8xXYdJS37jPXlQkSp5WYXRdeyEgPGfNZ654Jq+ysAZrzZVVhXp+DuTfCuuuk6gfyYEX4q8iKvbbjPUlxlpX27mEmq5u7wOGuj31fNn3ov94Q=,iv:9LCn45extQvBKZeWyslMMHZbrJnvYXLqpWyjF5D1UpM=,tag:5clOM8yL/nPRSQGhrq0LOA==,type:str]
    version: 3.13.1
