apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-stack-grafana 
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.vandesteeg.dev
      http:
        paths:
          - backend:
              service:
                name:  kube-prometheus-stack-grafana
                port:
                  number: 3000
            path: /
            pathType: Prefix

