apiVersion: v1
data:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:zh5Ax3C4mVZXtg3NtD2/FeVbi6OQUZLFPwBDsDNLKyQ=,iv:CXOTlRkjp8YeFL6nlXDPtGqQXCHhlFXeGLj2iHIxTPQ=,tag:9Vd5gV6QnWgecWy4C26vxw==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:pbzJCl12C4Q=,iv:0OBRkRS8xgWPvDH8M11mxcjBPSxLh1+iFJYCXcCvtVM=,tag:q5o3Vd/txH3jY+vZl7hqVg==,type:str]
kind: Secret
metadata:
    name: grafana-container-env
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ2xla3pEN1pjRHZwdEZp
            Z2RYMDVwNnowUVRaZUgvSlMxUU44S3JZTHl3Ck9IemdzNzNRZzZaOUlDc0hFcXhI
            aDcxMEFZWXR5VUFValRleEF3SXFHbjgKLS0tIGprYklRaUFPcWtlMzJMWWNndmk2
            TnA5djg5c2Q1VzliRGVwbmx3V2VxUTgKPRdqsQ33snJhbYbBMp1AiIArBGtbzq1c
            vZYKmAKwcbnCVAu7lnbp/psBeCWm4PllVHPwyYVsJ9tn/TAwcPLYZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y26s22ljsek3cprtnhyp6h2xpeldy5g33hlsuf924rnthnn9a5dsp2grjs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T11:54:40Z"
    mac: ENC[AES256_GCM,data:F0umFeXxcJaMM+FVpME/2S6bHo06Em4q1DZNg11gnE+20gB6IgNT8N7yx0hY786yGxkyB6F6G1e8V/8cjUaVgw2l3RSvY4KQ12WPDmrzM05MZLVjijA8shg4VIi08n32JC9iBDG61txDncYSJKCCNH7EchHneM/idzkm6Gy3BaU=,iv:/LLQF2YO6W4M7ZsZ+n0pExQUwvcteK/coVuCHbUQS18=,tag:IGFHdZ9iXi55DpgB5ZX2FA==,type:str]
    version: 3.13.1
